include:
  - project: "nstmrt/rubygems/templates"
    ref: master
    file: "build-rubygems.yml"

lint:
  stage: test
  image: ${BUILD_CONF_HARBOR_REGISTRY}/dhub/library/ruby:3.3
  tags:
    - paas-stage
  script:
    - bundle install
    - bundle exec rubocop

tests:
  stage: test
  image: ${BUILD_CONF_HARBOR_REGISTRY}/dhub/library/ruby:$RUBY_VERSION
  tags:
    - paas-medium
  parallel:
    matrix:
      - RUBY_VERSION: ['2.7', '3.0', '3.1', '3.2', '3.3']
  services:
    - name: ${BUILD_CONF_HARBOR_REGISTRY}/dhub/library/postgres:13
      alias: postgres
    - name: ${BUILD_CONF_HARBOR_REGISTRY}/dhub/library/redis:7
      alias: redis
  variables:
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: postgres://postgres:secret@postgres:5432
    REDIS_URL: redis://redis:6379/0
  before_script:
    - gem sources --remove https://rubygems.org/
    - gem sources --add ${NEXUS_PUBLIC_SOURCE_URL}
    - gem update --system 3.4.22
    - bin/setup
  script:
    - bundle exec appraisal rspec --format RspecJunitFormatter --out test-results/rspec_$RUBY_VERSION.xml --format documentation
  artifacts:
    reports:
      junit: test-results/rspec*.xml
