include:
  - project: "nstmrt/rubygems/templates"
    ref: master
    file: "build-rubygems.yml"

lint:
  stage: test
  image: ruby:3.2
  script:
    - bundle install
    - bundle exec rubocop

tests:
  stage: test
  image: ruby:$RUBY_VERSION
  parallel:
    matrix:
      - RUBY_VERSION: ['2.7', '3.0', '3.1', '3.2']
  services:
    - name: dreg.sbmt.io/dhub/library/postgres:12.2
      alias: postgres
    - name: dreg.sbmt.io/dhub/library/redis:7
      alias: redis
  variables:
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: postgres://postgres:secret@postgres:5432
    REDIS_URL: redis://redis:6379/0
  before_script:
    - bin/setup
  script:
    - bundle exec appraisal rspec --format RspecJunitFormatter --out test-results/rspec_$RUBY_VERSION.xml --format documentation
  artifacts:
    reports:
      junit: test-results/rspec*.xml
