inherit_from: .rubocop_todo.yml

# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 5.2
  NewCops: enable
  SuggestExtensions: false

require:
  # Performance cops are bundled with Standard
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  # Standard's config uses custom cops,
  # so it must be loaded
  - standard

inherit_gem:
  standard: config/base.yml

# rubocop-rails
Rails/SkipsModelValidations:
  Enabled: false

# rubocop-rspec
RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 10

RSpec/ExampleLength:
  Max: 35

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/DescribeClass:
  Exclude:
    - spec/lib/sbmt/outbox/tasks/*

RSpec/InstanceVariable:
  Exclude:
    # TODO: Remove this when changing the minimum Rails version to 5.1
    - spec/lib/sbmt/outbox/worker_spec.rb
