{
 "title": "Outbox / Inbox",
 "tags": [
  "outbox",
  "inbox",
  "ruby"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(outbox_created_counter,namespace)"
    }
   },
   {
    "name": "box_name",
    "label": "Box name",
    "query": {
     "query": "label_values(outbox_created_counter{namespace=\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Apdex",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(outbox_process_latency_seconds_bucket{namespace=\"$namespace\", name=~\"$box_name\", le=\"10\"}[$__rate_interval])) by (name)\n+\n  sum(rate(outbox_process_latency_seconds_bucket{namespace=\"$namespace\", name=~\"$box_name\", le=\"45\"}[$__rate_interval])) by (name)\n) / 2 / sum(rate(outbox_process_latency_seconds_count{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivery rate (rps)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(outbox_sent_counter{namespace=\"$namespace\", name=\"$box_name\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Item latency 75 pth (sec)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retried (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_retry_counter{namespace=\"$namespace\", name=\"$box_name\"}[5m])) / sum(increase(outbox_sent_counter{namespace=\"$namespace\", name=\"$box_name\"}[5m])) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retried total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_retry_counter{namespace=\"$namespace\", name=\"$box_name\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_error_counter{namespace=\"$namespace\", name=\"$box_name\"}[5m])) / sum(increase(outbox_sent_counter{namespace=\"$namespace\", name=\"$box_name\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(outbox_error_counter{namespace=\"$namespace\", name=\"$box_name\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Owner",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "max(outbox_created_counter{namespace=\"$namespace\",name=\"$box_name\"}) by (owner)"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Creating rate VS processing rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "items/s" } },
   "targets": [
    {
     "expr": "sum(rate(outbox_created_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "created"
    },
    {
     "expr": "sum(rate(outbox_sent_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "delivered"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "items/s" } },
   "targets": [
    {
     "expr": "sum(rate(outbox_error_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(outbox_retry_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "retried"
    },
    {
     "expr": "sum(rate(outbox_fetch_error_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "already processed"
    },
    {
     "expr": "sum(rate(inbox_error_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(inbox_retry_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "retried"
    },
    {
     "expr": "sum(rate(inbox_fetch_error_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "not found"
    }
   ]
  },
  {
   "title": "Queue latency apdex",
   "type": "timeseries",
   "description": "The difference in the time of creating an outbox item and processing",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(outbox_process_latency_seconds_bucket{namespace=\"$namespace\", name=~\"$box_name\", le=\"10\"}[$__rate_interval])) by (name)\n+\n  sum(rate(outbox_process_latency_seconds_bucket{namespace=\"$namespace\", name=~\"$box_name\", le=\"45\"}[$__rate_interval])) by (name)\n) / 2 / sum(rate(outbox_process_latency_seconds_count{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Queue latency",
   "type": "timeseries",
   "description": "The difference in the time of creating an outbox item and processing",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(outbox_process_latency_seconds_bucket{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (le, name))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(outbox_process_latency_seconds_bucket{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (le, name))",
     "legendFormat": "95"
    },
    {
     "expr": "sum(rate(outbox_process_latency_seconds_sum{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name) / sum(rate(outbox_process_latency_seconds_count{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Queue lag increase",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "items" } },
   "targets": [
    {
     "expr": "sum(increase(outbox_created_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name) - sum(increase(outbox_sent_counter{namespace=\"$namespace\", name=~\"$box_name\"}[$__rate_interval])) by (name) >= 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "sum(rate(box_worker_item_execution_runtime_seconds_sum{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(box_worker_item_execution_runtime_seconds_count{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Worker V2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Poll runtime (p95) per partition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_job_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\", worker_name=\"poller\"}[$__rate_interval])) by (le, partition))",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Process bucket runtime (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_job_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\", worker_name=\"processor\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "DB replica reqs/poll per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(box_worker_batches_per_poll_counter{name=~\"$box_name\", namespace=\"$namespace\", worker_version=\"2\"}[1m])) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Items per poll cycle (avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(increase(box_worker_job_items_counter{name=~\"$box_name\", namespace=\"$namespace\", worker_version=\"2\", worker_name=\"poller\"}[$__rate_interval]))",
     "legendFormat": "items per poll"
    }
   ]
  },
  {
   "title": "Poll throttle",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(box_worker_poll_throttling_counter{name=~\"$box_name\", namespace=\"$namespace\", worker_version=\"2\", status != \"noop\"}[$__rate_interval])) by (throttler)\n/ \nsum(rate(box_worker_poll_throttling_counter{name=~\"$box_name\", namespace=\"$namespace\", worker_version=\"2\"}[$__rate_interval])) by (throttler)",
     "legendFormat": "{{throttler}}"
    }
   ]
  },
  {
   "title": "Poll throttle cycle runtime (p95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_poll_throttling_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (partition, le))",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Redis job-queue time-lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(box_worker_redis_job_queue_time_lag{name=~\"$box_name\", namespace=\"$namespace\", worker_version=\"2\"}[$__rate_interval]) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Redis job-queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(box_worker_redis_job_queue_size{name=~\"$box_name\", namespace=\"$namespace\", worker_version=\"2\"}[$__rate_interval]) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Worker metrics by item", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Processing item rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (name, partition) (rate(box_worker_job_items_counter{name=~\"$box_name\", namespace=~\"$namespace\", worker_version != \"2\"}[$__rate_interval]))",
     "legendFormat": "{{partition}}"
    },
    {
     "expr": "sum by (name) (rate(box_worker_job_items_counter{name=~\"$box_name\", namespace=~\"$namespace\", worker_version = \"2\", worker_name=\"processor\"}[$__rate_interval]))",
     "legendFormat": "$box_name"
    }
   ]
  },
  {
   "title": "Processing item latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\", worker_version != \"2\"}[$__rate_interval])) by (le, partition))",
     "legendFormat": "{{partition}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\", worker_version = \"2\", worker_name=\"processor\"}[$__rate_interval])) by (le, partition))",
     "legendFormat": "$box_name"
    }
   ]
  },
  {
   "title": "Processing item rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (name, pod) (rate(box_worker_job_items_counter{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing item latency by pod (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mean processing item latency by partition (95th percentile)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_item_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\", worker_version != \"2\"}[$__rate_interval])) by (le, partition))",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  { "title": "Worker metrics by batch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Average batch size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "items" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(outbox_sent_counter{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) / sum by (name) (rate(box_worker_job_counter{state=\"processed\", name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "batch"
    },
    {
     "expr": "sum by (name) (rate(inbox_sent_counter{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) / sum by (name) (rate(box_worker_job_counter{state=\"processed\", name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "batch"
    }
   ]
  },
  {
   "title": "Processing batch rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(box_worker_job_counter{state=\"processed\", name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Processing batch latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_job_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(box_worker_job_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "sum(rate(box_worker_job_execution_runtime_seconds_sum{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) / sum(rate(box_worker_job_execution_runtime_seconds_count{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Processing batch rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job,pod) (rate(box_worker_job_counter{state=\"processed\", name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing batch latency by pod (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(box_worker_job_execution_runtime_seconds_bucket{name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error rate by partition",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(box_worker_job_counter{state=\"failed\", name=~\"$box_name\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Skipping batch rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (name, partition) (rate(box_worker_job_counter{state=\"skipped\", name=~\"$box_name\", namespace=~\"$namespace\", worker_version != \"2\"}[$__rate_interval]))",
     "legendFormat": "{{partition}}"
    },
    {
     "expr": "sum by (name) (rate(box_worker_job_counter{state=\"skipped\", name=~\"$box_name\", namespace=~\"$namespace\", worker_version = \"2\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Scheduler metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Schked tasks rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(schked_jobs_executed_total{namespace=\"$namespace\",success=\"true\",name=~\"Sbmt::Outbox::.*\"}[1m])) by (name)",
     "legendFormat": "Successful – {{name}}"
    },
    {
     "expr": "sum(rate(schked_jobs_executed_total{namespace=\"$namespace\",success=\"false\",name=~\"Sbmt::Outbox::.*\"}[1m])) by (name)",
     "legendFormat": "Failed – {{name}}"
    }
   ]
  },
  {
   "title": "Sidekiq jobs rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sidekiq_jobs_success_total{namespace=\"$namespace\", worker=~\"Sbmt::Outbox::.*\"}[1m])) by (worker)",
     "legendFormat": "{{worker}}::success"
    },
    {
     "expr": "sum(rate(sidekiq_jobs_failed_total{namespace=\"$namespace\", worker=~\"Sbmt::Outbox::.*\"}[1m])) by (worker)",
     "legendFormat": "{{worker}}::fail"
    },
    {
     "expr": "sum(rate(inbox_requeue_counter{namespace=\"$namespace\", name=~\"$name\"}[1m]))",
     "legendFormat": "Requeued – {{name}}"
    }
   ]
  }
 ]
}