default: &default
  kafka:
    required_acks: -1

  items:
    outbox_item:
      max_retries: 1

  producer:
    topics:
      order_created: orders

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
