test:
  bucket_size: 4

  kafka:
    required_acks: -1

  outbox_items:
    outbox_item:
      partition_size: 2
      partition_strategy: number
      retention: P1W
      retry_strategies:
        - exponential_backoff
        - compacted_log

  inbox_items:
    inbox_item:
      partition_size: 2
      partition_strategy: number
      retention: P1W
      retry_strategies:
        - exponential_backoff

  producer:
    topics:
      order_created: orders
