test:
  bucket_size: 4

  outbox_items:
    outbox_item:
      partition_size: 2
      partition_strategy: number
      retention: P1W
      retry_strategies:
        - exponential_backoff
        - compacted_log
      transports:
        kafka_producer:
          topic: "outbox_item_topic"
          kafka:
            required_acks: -1

  inbox_items:
    inbox_item:
      partition_size: 2
      partition_strategy: number
      retention: P1W
      retry_strategies:
        - exponential_backoff
      transports:
        import_order:
          source: "kafka_consumer"
