default: &default
  kafka:
    required_acks: -1

  items:
    outbox_item:
      retention: P1W
      retry_strategies:
        - exponential_backoff
        - compacted_log

  producer:
    topics:
      order_created: orders

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
