name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: "3.3"
    name: Rubocop
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby w/ same version as image
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Install dependencies
        run: |
          gem install dip
          dip bundle install
      - name: Run linter
        run: dip rubocop
